### ISSUE TITLE
Migrate playground build to Vite

### ISSUE THREAD

**Issue by ad1992** [excalidraw/mermaid-to-excalidraw#36]
Currently it in pure JS so we are missing out the features such as hot reload and additionally since we are using Vite else where it would be better to move the playground to Vite as well

**Comment by akshbswas98** [comment]
@ad1992 Can you assign this to me asap

**Comment by ad1992** [comment]
> @ad1992 Can you assign this to me asap

Sure go ahead! Check out for [aakansha/sequence](https://github.com/excalidraw/mermaid-to-excalidraw/pull/34) as I have made some changes to playground and will be merging that very soon

**Comment by ad1992** [comment]
@akshbswas98 any update on this ?

**Comment by igorwessel** [comment]
@ad1992 Can you assign it to me?

**Comment by ad1992** [comment]
Go for it @igorwessel 🚀
