### ISSUE TITLE
\n in mermaid text renders as \n instead of newline

### ISSUE THREAD

**Issue by skycloudd** [excalidraw/mermaid-to-excalidraw#47]
A `\n` in Mermaid code isnt converted to an actual newline when converted to an Excalidraw diagram

For example:

```
classDiagram
    note "test 123\ntest 456"
```

Is converted to:

<img width="133" alt="image" src="https://github.com/excalidraw/mermaid-to-excalidraw/assets/51929172/0d0f1efa-838e-40ce-abc7-3a2747c9ef45">

I expect `test 456` to be on a new line.

**Comment by igorwessel** [comment]
@ad1992 wee have anything equivalent in the codebase to convert these escape sequences? 
```json
{
  "type": "class",
  "nodes": [
    [
      {
        "type": "rectangle",
        "id": "note0",
        "label": {
          "text": "test 123\\ttest 456",
          "fontSize": 16
        },
        "x": 8,
        "y": 8,
        "width": 214.73333740234375,
        "height": 44.5,
        "subtype": "note",
        "strokeStyle": "dashed"
      }
    ]
  ],
  "lines": [],
  "arrows": [],
  "text": [],
  "namespaces": {}
}
```
