### ISSUE TITLE
create participant / create actor not working 

### ISSUE THREAD

**Issue by kobe651jp** [excalidraw/mermaid-to-excalidraw#48]
The following code not working.

---
sequenceDiagram
    Alice->>Bob: Hello Bob, how are you ?
    Bob->>Alice: Fine, thank you. And you?
    create participant Carl
    Alice->>Carl: Hi Carl!
    create actor D as Donald
    Carl->>D: Hi!
    destroy Carl
    Alice->>Carl: We are too many
    destroy Bob
    Bob->>Alice: I agree

---

```mermaid
sequenceDiagram
    Alice->>Bob: Hello Bob, how are you ?
    Bob->>Alice: Fine, thank you. And you?
    create participant Carl
    Alice->>Carl: Hi Carl!
    create actor D as Donald
    Carl->>D: Hi!
    destroy Carl
    Alice->>Carl: We are too many
    destroy Bob
    Bob->>Alice: I agree

```
Is this a known thing?

**Comment by ad1992** [comment]
This was fixed in #46
