### ISSUE TITLE
vercel deploy problem 

### ISSUE THREAD

**Issue by li-yingfei** [excalidraw/mermaid-to-excalidraw#62]
Hi, I have a problem with deploying the code on vercel. There are some picture for my process. Could you give some advice? Thanks!
![WechatIMG12997](https://github.com/excalidraw/mermaid-to-excalidraw/assets/115736862/8a080cf6-3115-430f-af1e-7435af456b29)
![WechatIMG12998](https://github.com/excalidraw/mermaid-to-excalidraw/assets/115736862/e34fbd83-843e-43b5-a097-193a8cccfbbb)
![WechatIMG12999](https://github.com/excalidraw/mermaid-to-excalidraw/assets/115736862/fb0698db-1d71-4c3b-b090-f8eecacb01ea)
![WechatIMG13001](https://github.com/excalidraw/mermaid-to-excalidraw/assets/115736862/a0d2cb3a-81da-468d-8338-693dc77db58b)

**Comment by li-yingfei** [comment]
Thanks a lot! There is still some problem here maybe about the output directory. Could you please also tell me how to config output directory, install command and development command? Thanks!
![WechatIMG13437](https://github.com/excalidraw/mermaid-to-excalidraw/assets/115736862/b402b767-e748-4e9e-83d8-d674d69ddf05)
![WechatIMG13441](https://github.com/excalidraw/mermaid-to-excalidraw/assets/115736862/f7a4bf25-2580-4ff5-9a51-0797c81aeaae)

**Comment by li-yingfei** [comment]
And here is the picture that made by some people successfully deploy. Should I add environment variable?
![WechatIMG13528](https://github.com/excalidraw/mermaid-to-excalidraw/assets/115736862/619a199a-fe8c-4553-a230-38adf9fe7ed4)

**Comment by ad1992** [comment]
@li-yingfei the output directory is `public` also mark check the below option 👇🏻 

<img width="882" alt="Screenshot 2024-05-08 at 7 22 28 PM" src="https://github.com/excalidraw/mermaid-to-excalidraw/assets/11256141/8a659e0c-c351-44ac-8508-bd075c186d2c">

**Comment by li-yingfei** [comment]
Ok Thanks!

**Comment by ad1992** [comment]
closing this as its resolved
